name: practix-analytics
services:

  ugc:
    container_name: movies-ugc
    image: movies-ugc:latest
    env_file:
      - ./ugc/.env
    environment:
      - KAFKA_HOST=${KAFKA_BROKER_NAME_0}
      - KAFKA_PORT=${KAFKA_INTERNAL_PORT}
      - SENTRY_DSN=${SENTRY_DSN}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
    build:
      context: ./ugc/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      kafka-init:
        condition: service_started
    networks:
      - kafka_network

  etl_analytics_events:
    container_name: etl_analytics_events
    image: etl_analytics:latest
    build:
      context: ./etl_analytics/
      dockerfile: Dockerfile
    env_file:
      - ./etl_analytics/.env
    environment:
      - KAFKA_HOST=${KAFKA_BROKER_NAME_0}
      - KAFKA_PORT=${KAFKA_INTERNAL_PORT}
      - KAFKA_TOPIC=${KAFKA_TOPIC_NAME_1}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USERNAME=${CLICKHOUSE_USERNAME}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      kafka-init:
        condition: service_started
    networks:
      - kafka_network

  kafka-0:
    image: bitnami/kafka:${KAFKA_VERSION}
    container_name: ${KAFKA_BROKER_NAME_0}
    ports:
      - ${KAFKA_BROKER_0_EXTERNAL_PORT}:${KAFKA_BROKER_0_EXTERNAL_PORT}
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@${KAFKA_BROKER_NAME_0}:${KAFKA_CONTROLLER_PORT},1@${KAFKA_BROKER_NAME_1}:${KAFKA_CONTROLLER_PORT},2@${KAFKA_BROKER_NAME_2}:${KAFKA_CONTROLLER_PORT}
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_INTERNAL_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_BROKER_0_EXTERNAL_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_BROKER_NAME_0}:${KAFKA_INTERNAL_PORT},EXTERNAL://127.0.0.1:${KAFKA_BROKER_0_EXTERNAL_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_0_data:/bitnami/kafka
    healthcheck:
      test: kafka-topics.sh --bootstrap-server localhost:${KAFKA_BROKER_0_EXTERNAL_PORT} --list
      interval: 1s
      timeout: 60s
      retries: 60
    networks:
      - kafka_network

  kafka-1:
    image: bitnami/kafka:${KAFKA_VERSION}
    container_name: ${KAFKA_BROKER_NAME_1}
    ports:
      - ${KAFKA_BROKER_1_EXTERNAL_PORT}:${KAFKA_BROKER_1_EXTERNAL_PORT}
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@${KAFKA_BROKER_NAME_0}:${KAFKA_CONTROLLER_PORT},1@${KAFKA_BROKER_NAME_1}:${KAFKA_CONTROLLER_PORT},2@${KAFKA_BROKER_NAME_2}:${KAFKA_CONTROLLER_PORT}
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_INTERNAL_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_BROKER_1_EXTERNAL_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_BROKER_NAME_1}:${KAFKA_INTERNAL_PORT},EXTERNAL://127.0.0.1:${KAFKA_BROKER_1_EXTERNAL_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_1_data:/bitnami/kafka
    networks:
      - kafka_network

  kafka-2:
    image: bitnami/kafka:${KAFKA_VERSION}
    container_name: ${KAFKA_BROKER_NAME_2}
    ports:
      - ${KAFKA_BROKER_2_EXTERNAL_PORT}:${KAFKA_BROKER_2_EXTERNAL_PORT}
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@${KAFKA_BROKER_NAME_0}:${KAFKA_CONTROLLER_PORT},1@${KAFKA_BROKER_NAME_1}:${KAFKA_CONTROLLER_PORT},2@${KAFKA_BROKER_NAME_2}:${KAFKA_CONTROLLER_PORT}
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_INTERNAL_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_BROKER_2_EXTERNAL_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_BROKER_NAME_2}:${KAFKA_INTERNAL_PORT},EXTERNAL://127.0.0.1:${KAFKA_BROKER_2_EXTERNAL_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_2_data:/bitnami/kafka
    networks:
      - kafka_network

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    ports:
      - ${KAFKA_UI_EXTERNAL_PORT}:${KAFKA_UI_EXTERNAL_PORT}
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:${KAFKA_INTERNAL_PORT}
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - kafka_network

  kafka-init:
    image: bitnami/kafka:${KAFKA_VERSION}
    depends_on:
      kafka-0:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e blocks until kafka is reachable
      kafka-topics.sh --bootstrap-server ${KAFKA_BROKER_NAME_0}:${KAFKA_INTERNAL_PORT} --list

      echo -e 'Creating kafka topics'
      kafka-topics.sh --bootstrap-server ${KAFKA_BROKER_NAME_0}:${KAFKA_INTERNAL_PORT} --create --if-not-exists --topic ${KAFKA_TOPIC_NAME_1} --replication-factor ${KAFKA_TOPIC_1_REPLICATION_FACTOR} --partitions ${KAFKA_TOPIC_1_PARTITIONS} --config retention.ms=${KAFKA_TOPIC_1_RETENTIONS_MS}

      echo -e 'Successfully created the following topics:'
      kafka-topics.sh --bootstrap-server ${KAFKA_BROKER_NAME_0}:${KAFKA_INTERNAL_PORT} --list
      "
    networks:
      - kafka_network

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data:

networks:
  kafka_network:
    driver: bridge