### Create review by film. Send POST request.
POST http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

{
  "text": "Рецензия к фильму."
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


### Without key: check response status is 404
POST http://127.0.0.1:5000/api/v1/reviews
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

{
  "text": "Рецензия к фильму."
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}


### Without text: check response status is 400
POST http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}


### Without key: check response status is 404
POST http://127.0.0.1:5000/api/v1/reviews
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

{
  "text": "Рецензия к фильму."
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}


### Without access_token: check response status is 403
POST http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json

{
  "text": "Рецензия к фильму."
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}


### Expired access_token: check response status is 403
POST http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json
Cookie: access_token={{expired_access_token}}

{
  "text": "Рецензия к фильму."
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}


### Invalid access_token: check response status is 403
POST http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json
Cookie: access_token={{invalid_access_token}}

{
  "text": "Рецензия к фильму."
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}


### Validated error access_token data: check response status is 403
POST http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json
Cookie: access_token={{user_login_access_token}}

{
  "text": "Рецензия к фильму."
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}


### Get list review films. Send GET request
GET http://127.0.0.1:5000/api/v1/reviews
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Get review. Send GET request
GET http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Update review. Send PATCH request
PATCH http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

{
  "text": "Обновленная рецензия к фильму"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Not found: check response status is 404
PATCH http://127.0.0.1:5000/api/v1/reviews/{{not_found_uuid}}
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

{
  "text": "Обновленная рецензия к фильму"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}


### Delete review. Send DELETE request with json body
DELETE http://127.0.0.1:5000/api/v1/reviews/{{film_id}}
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}


### Not found: check response status is 404
DELETE http://127.0.0.1:5000/api/v1/reviews/{{not_found_uuid}}
Content-Type: application/json
Cookie: access_token={{valid_access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}
