version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ugc_db
      - POSTGRES_USER=ugc_user
      - POSTGRES_PASSWORD=ugc_password


